## Get actual location of zshrc file from dotfiles (of course from stackoverflow)
DOTFILE_ZSH_DIR="$(dirname "$(readlink -f "$HOME/.zshrc")")"

## folder of all of own autocomplete functions
fpath=($HOME/.zsh/completions $fpath)

## Enable autocompletions
autoload -Uz compinit
typeset -i updated_at=$(date +'%j' -r ~/.zcompdump 2>/dev/null || stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)
if [ $(date +'%j') != $updated_at ]; then
  compinit -i
else
  compinit -C -i
fi
zmodload -i zsh/complist

### Options
# activate correction
setopt correct_all
setopt auto_list # list choice on an ambigious completion
setopt auto_menu # automatically use menu completion 
setopt always_to_end # move cursor to end if word has one match
setopt interactive_comments # allow comments in interactive shells
setopt completeinword # complete inside words
setopt nolistambiguous # only list matches if ambiguous
setopt nolistbeep # don't beep on ambiguous listings

## enable warning message of zsh completions
zstyle ':completion:*' verbose yes 
zstyle ':completion:*:warnings' format 'No matches for: %d'
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache
# according to the internet, this should make zsh much faster
zstyle ':completion:*' accept-exact '*(N)'


## load antibody plugins
source ~/.zsh_plugins.sh
## load settings for space ship prompt
source $DOTFILE_ZSH_DIR/space_ship_prompt.zsh
## load fuzzy autocomplition, zstyle...
source $DOTFILE_ZSH_DIR/completion.zsh
## load directory features, autopushd, autocd, ...
source $DOTFILE_ZSH_DIR/directory.zsh
## load history features
source $DOTFILE_ZSH_DIR/history.zsh
## load ls colors
source $DOTFILE_ZSH_DIR/ls_colors.zsh

## setup fuzzy finder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

## Map caps lock to ctrl
setxkbmap -layout us -option ctrl:nocaps                                                                                                  

## Switch on vi keybindings
KEYTIMEOUT=1 # 10ms for key sequences, default is 0.4s
bindkey -v

## for thefuck: Magnificent app which corrects your previous console command
eval $(thefuck --alias)

## setup pyenv if pyenv is installed
if [ -f $HOME/.pyenv/bin/pyenv ]; then
  export PATH="$HOME/.pyenv/bin:$PATH"
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi

## alias to update antibody plugins for static loading
alias zsh_plugin_update='antibody bundle < ~/.zsh_plugins.txt > ~/.zsh_plugins.sh && antibody update'


export WERKSTATT="/home/althofda/werkstatt"
source $WERKSTATT/.werkstattrc.bash
